name: 'Jira Issue Check'
inputs:
  branch-name:  # New input for the branch name
    description: 'The branch name passed from the calling workflow.'
    required: false
  jira-base-url:
    description: 'The base URL for the self-hosted Jira instance.'
    required: true
  jira-token:
    description: 'The API token for authentication.'
    required: true
  pr-body:
    description: 'Pull Request description'
    required: true
runs:
  using: "composite"
  steps:
    # - name: 📦 Install utilities
    #   run: sudo apt-get update && sudo apt-get install -y jq curl
    - name: Validate PR Description Includes Issue Key
      id: extract_key
      shell: bash
      run: |
        PR_BODY="${{ inputs.pr-body }}"
        echo "PR Description received:"
        echo "$PR_BODY"

        ISSUE_KEYS=$(echo "$PR_BODY" | grep -oE '[A-Z]+-[0-9]+' | sort -u)
        
        if [[ -z "$ISSUE_KEYS" ]]; then
          echo "❌ No Jira issue keys found in PR description."
          exit 1
        fi
    
        echo "✅ PR description includes Jira key."
        KEYS_CSV=$(echo "$ISSUE_KEYS" | paste -sd "," -)
        echo "issue_key=$KEYS_CSV" >> $GITHUB_OUTPUT

    - name: 📞 Get Jira Issue Status and Validate
      if: steps.extract_key.outputs.issue_key != ''
      id: get_and_check_status
      shell: bash
      run: |
        FAIL=false
        SUMMARY="## Jira Issue Statuses\n"
        OUTPUT_FILE=$(mktemp)
        DELIMITER="EOF_JIRA_SUMMARY"
        echo "## Jira Issue Statuses" >> "$OUTPUT_FILE"
        IFS=',' read -ra KEYS <<< "${{ steps.extract_key.outputs.issue_key }}"
      
        for ISSUE_KEY in "${KEYS[@]}"; do
          echo "🔍 Checking Jira Issue: $ISSUE_KEY"
      
          JIRA_URL="${{ inputs.jira-base-url }}"
          JIRA_AUTH="${{ inputs.jira-token }}"
      
          HTTP_STATUS=$(curl -s -o /tmp/jira_response.json -w "%{http_code}" \
            --location --request GET "${JIRA_URL}/rest/api/2/issue/$ISSUE_KEY?fields=status" \
            --header 'Accept: application/json' \
            --header "Authorization: Bearer $JIRA_AUTH" )
      
          echo "Jira API HTTP Status: $HTTP_STATUS"
      
          if [ "$HTTP_STATUS" -ne 200 ]; then
            SUMMARY+="❌ **$ISSUE_KEY** → Error (HTTP $HTTP_STATUS)\n"
            FAIL=true
            continue
          fi
      
          STATUS=$(jq -r '.fields.status.name' /tmp/jira_response.json)
          TITLE=$(jq -r '.fields.summary' /tmp/jira_response.json)
          SUMMARY+="- **$ISSUE_KEY** → $STATUS\n"
          echo "✔ $ISSUE_KEY Status: $STATUS"
          # echo "- **$ISSUE_KEY** → $STATUS" >> "$OUTPUT_FILE"
          echo "- **$ISSUE_KEY**: $TITLE → \`$STATUS\`" >> "$OUTPUT_FILE"
          
          if [[ "$STATUS" != "Done" ]]; then
            echo "❌ Issue $ISSUE_KEY is '$STATUS'. Must be 'Done'."
            FAIL=true
          else
            echo "✅ $ISSUE_KEY is Done"
          fi
        done
        # Export summary to next step
        # Escape newlines for GitHub output
        SUMMARY_ESCAPED=$(printf "%s" "$SUMMARY" | sed ':a;N;$!ba;s/\n/%0A/g')
        # echo "summary=$SUMMARY_ESCAPED" >> $GITHUB_OUTPUT
        echo "summary<<$DELIMITER" >> "$GITHUB_OUTPUT"
        
        # Cat the entire file content into the output block
        cat "$OUTPUT_FILE" >> "$GITHUB_OUTPUT"
        
        # End the $GITHUB_OUTPUT block with the same delimiter
        echo "$DELIMITER" >> "$GITHUB_OUTPUT"
        if [ "$FAIL" = true ]; then
          echo "❌ One or more Jira issues are not 'Done'."
          exit 1
        else
          echo "🎉 All Jira issues are 'Done'!"
        fi
    - name: Comment Jira Statuses on PR
      if: always()
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.get_and_check_status.outputs.summary }}
